# Generated by Django 4.2 on 2023-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='dia',
            field=models.DateField(auto_now=False, verbose_name='dia'),
        ),
        migrations.AddField(
            model_name='texto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/texto'),
        ),
    ]
